import React from 'react';
import { Download, Share2, Copy, Check } from 'lucide-react';
import { GeneratedLogo } from '../types';

interface ResultDisplayProps {
  logo: GeneratedLogo | null;
  isLoading: boolean;
}

const ResultDisplay: React.FC<ResultDisplayProps> = ({ logo, isLoading }) => {
  const [copied, setCopied] = React.useState(false);

  const handleCopyPrompt = () => {
    if (logo) {
      navigator.clipboard.writeText(logo.promptUsed);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  if (isLoading) {
    return (
      <div className="h-full min-h-[400px] flex flex-col items-center justify-center bg-slate-900/30 rounded-2xl border border-white/10 p-8 animate-pulse">
        <div className="w-24 h-24 rounded-full bg-slate-800 mb-4 animate-bounce opacity-50"></div>
        <p className="text-slate-500 font-medium">Crafting your masterpiece...</p>
        <p className="text-slate-600 text-sm mt-2">AI is experimenting with shapes and colors</p>
      </div>
    );
  }

  if (!logo) {
    return (
      <div className="h-full min-h-[400px] flex flex-col items-center justify-center bg-slate-900/30 rounded-2xl border border-white/5 border-dashed p-8">
        <div className="w-16 h-16 rounded-full bg-slate-800/50 flex items-center justify-center mb-4">
          <svg className="w-8 h-8 text-slate-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
        </div>
        <h3 className="text-slate-400 font-medium mb-1">No Logo Generated Yet</h3>
        <p className="text-slate-600 text-sm text-center max-w-xs">
          Fill out the form on the left to start your brand journey with Zyro Designer AI.
        </p>
      </div>
    );
  }

  const handleDownload = () => {
    const link = document.createElement('a');
    link.href = logo.imageUrl;
    link.download = `zyro-logo-${Date.now()}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleShare = async () => {
    try {
      // Create a blob from the base64 data to share as a file
      const response = await fetch(logo.imageUrl);
      const blob = await response.blob();
      const file = new File([blob], 'zyro-logo.png', { type: 'image/png' });

      if (navigator.share && navigator.canShare({ files: [file] })) {
        await navigator.share({
          title: 'Zyro Designer AI Logo',
          text: `I just created this logo with Zyro Designer AI using the prompt: "${logo.promptUsed}"`,
          files: [file],
        });
      } else {
        // Fallback for browsers that don't support file sharing
        await navigator.clipboard.writeText(logo.promptUsed);
        alert('Sharing not supported on this device/browser. Prompt copied to clipboard!');
      }
    } catch (error) {
      console.error('Error sharing:', error);
      // Fallback
      await navigator.clipboard.writeText(logo.promptUsed);
      alert('Prompt copied to clipboard!');
    }
  };

  return (
    <div className="space-y-6">
      <div className="relative group rounded-2xl overflow-hidden border border-white/10 shadow-2xl bg-slate-950">
        <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-20 pointer-events-none"></div>
        <img
          src={logo.imageUrl}
          alt="Generated Logo"
          className="w-full h-auto object-contain max-h-[500px] bg-slate-900"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex items-end justify-center p-6">
           <p className="text-white/80 text-sm font-medium">Generated by Gemini 2.5 Flash</p>
        </div>
      </div>

      <div className="flex flex-col sm:flex-row gap-4">
        <button 
          onClick={handleDownload}
          className="flex-1 flex items-center justify-center gap-2 bg-slate-800 hover:bg-slate-700 text-white px-6 py-3 rounded-xl font-medium transition-all border border-slate-700"
        >
          <Download className="w-4 h-4" />
          Download High Res
        </button>
        <button 
          onClick={handleShare}
          className="flex items-center justify-center gap-2 bg-slate-900 hover:bg-slate-800 text-slate-300 px-6 py-3 rounded-xl font-medium transition-all border border-slate-800"
        >
          <Share2 className="w-4 h-4" />
          Share
        </button>
      </div>
      
      <div className="bg-slate-900/50 rounded-xl p-4 border border-white/5">
        <div className="flex items-center justify-between mb-2">
            <span className="text-xs uppercase tracking-wider text-slate-500 font-bold">Prompt Used</span>
            <button 
              onClick={handleCopyPrompt}
              className="text-slate-500 hover:text-indigo-400 transition-colors"
              title="Copy prompt"
            >
              {copied ? <Check className="w-3 h-3 text-green-500" /> : <Copy className="w-3 h-3" />}
            </button>
        </div>
        <p className="text-xs text-slate-400 leading-relaxed font-mono">
            {logo.promptUsed.slice(0, 150)}...
        </p>
      </div>
    </div>
  );
};

export default ResultDisplay;